spring.application.name=red-pocket
spring.datasource.url=jdbc:sqlserver://127.0.0.1;databaseName=red-pocket;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=p@ssw0rd
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver


spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update

#開放所有監控端點 (開發環境可以用，正式環境要鎖起來)
management.endpoints.web.exposure.include=*

# 讓 health 顯示詳細資訊（可以看到 Redis、DB 的連線狀態）
# url：http://localhost:8080/actuator/health
management.endpoint.health.show-details=always


# RabbitMQ 設定
spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# 程式跑完(沒exception)，就自動把 MQ內資料刪除
spring.rabbitmq.listener.simple.acknowledge-mode=auto
# 同時最多處理幾筆
spring.rabbitmq.listener.simple.prefetch=10
# 開啟重試機制
spring.rabbitmq.listener.simple.retry.enabled=true
# 最大重試 3 次
spring.rabbitmq.listener.simple.retry.max-attempts=3
# 重試間隔 1 秒起跳
spring.rabbitmq.listener.simple.retry.initial-interval=1000
# 下面這行代表同時有 5 個執行緒在跑 handleGrabMessage
spring.rabbitmq.listener.simple.concurrency=5

