events {
    worker_connections 4096;
}

http {

    # 限流設定：每個 IP 每秒最多 50 個請求
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=100r/s;
    
    upstream springboot {
       
        # 優先打連線數最少的 container
        least_conn; 
        server app:8080;
    }

    server {
        listen 80;

        location / {
        
            # 超過這個才 503
            proxy_connect_timeout 3s;
            proxy_read_timeout 5s;
        
            # 自訂 503 訊息
            error_page 503 /503.json;
        
        
            # 剩餘的排隊 可排1000人
            limit_req zone=api_limit burst=200 nodelay;
            proxy_pass http://springboot;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}